# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec2d699f9428b78062c93e9ae25eb3476817ebda14819dfc792a7c4b9970b58c0882c3d4cf329426e0ef9a111d1daa8e69726ccb88b7524c031aefac9ec68ccf

test:
  secret_key_base: c96a19d9af6fa818d386a7a5442c5c18b4aca062df23ca32497185439ec08d34f623b56f29c1214575f2af14e8d3b88fce0798eaa398783dc8c9db836280e4b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
